pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Dockerize') {
            steps {
                sh 'docker build -t travelmanagementsolution .'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 9090:9090 travelmanagementsolution'
            }
        }
    }
}
